export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY='GET_CATEGORY';
export const CREATE_CATEGORY='CREATE_CATEGORY';
export const UPDATE_CATEGORY='UPDATE_CATEGORY';
export const DELETE_CATEGORY='DELETE_CATEGORY';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';
export const CATEGORY_ERROR='CATEGORY_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

